FROM debian:buster


# Install required packages (wget and gnupg)
RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    ca-certificates \
    apt-transport-https \
    npm \
    --no-install-recommends

#Install Google Chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - 
#RUN sg -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
RUN apt-get update && apt-get install -y google-chrome-stable 

# Cleanup
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set Chrome as the default browser
RUN update-alternatives --install /usr/bin/x-www-browser x-www-browser /usr/bin/google-chrome-stable 200 \
    && update-alternatives --install /usr/bin/gnome-www-browser gnome-www-browser /usr/bin/google-chrome-stable 200

# Development image with all the Node.js stuff in it
FROM node:latest

# Set working directory, will be created if it does not exist
WORKDIR /usr/src/app

# Install application dependencies
COPY package.json ./
RUN npm install

# Copy application code
COPY . .

# Info to devs and others that this container needs to have port 4200 exposed externally,
# i.e. this instruction does not do anything more than info
EXPOSE 4200

# Start app
CMD ["npm", "start"]
